### ISSUE TITLE
close connection to db

### ISSUE THREAD

**Issue by PaSe85** [gewv-tu-dresden/timeseries-client#5]
der InfluxDBclient hat eine Funktion close() -> muss die Verknüpfung von unserem client zu der influxclientfkt noch erstellt werden? - ich dacht der Timeseriesclient stammt von dem INfluxclient ab..> da müsste er ja die Funktion auch haben? 
oder ich habe nach dem falschen befehl gesucht...

**Comment by karlTGA** [comment]
The new version of the influx db client don't need to connect to the server explicit. The request are stateless and made with every query. So a `connect` or `close` functions are not necessary. You can check the server with the `health` method.
